const apple = require("../assets/icons/apple.png");
const back = require("../assets/icons/back.png")
const burger = require("../assets/icons/burger.png")
const call = require("../assets/icons/call.png")
const calories = require("../assets/icons/calories.png")
const cancel = require("../assets/icons/cancel.png")
const cart = require("../assets/icons/cart.png")
const check_circle = require("../assets/icons/check_circle.png")
const check_off = require("../assets/icons/check_off.png")
const check_on = require("../assets/icons/check_on.png")
const cherry = require("../assets/icons/cherry.png")
const clock = require("../assets/icons/clock.png")
const correct = require("../assets/icons/correct.png")
const coupon = require("../assets/icons/coupon.png")
const cross = require("../assets/icons/cross.png")
const delete_icon = require("../assets/icons/delete.png")
const discount = require("../assets/icons/discount.png")
const dollar = require("../assets/icons/dollar.png")
const dotted_line = require("../assets/icons/dotted_line.png")
const down_arrow = require("../assets/icons/down_arrow.png")
const eye = require("../assets/icons/eye.png")
const eye_close = require("../assets/icons/eye_close.png")
const favourite = require("../assets/icons/favourite.png")
const fb = require("../assets/icons/fb.png")
const filter = require("../assets/icons/filter.png")
const focus = require("../assets/icons/focus.png")
const globe = require("../assets/icons/globe.png")
const google = require("../assets/icons/google.png")
const help = require("../assets/icons/help.png")
const home = require("../assets/icons/home.png")
const location = require("../assets/icons/location.png")
const location_pin = require("../assets/icons/location_pin.png")
const logout = require("../assets/icons/logout.png")
const love = require("../assets/icons/love.png")
const map = require("../assets/icons/map.png")
const mastercard = require("../assets/icons/mastercard.png")
const menu = require("../assets/icons/menu.png")
const minus = require("../assets/icons/minus.png")
const navigator = require("../assets/icons/navigator.png")
const navigator1 = require("../assets/icons/navigator1.png")
const paypal = require("../assets/icons/paypal.png")
const notification = require("../assets/icons/notification.png")
const paypal = require("../assets/icons/paypal.png")
const plus = require("../assets/icons/plus.png")
const profile = require("../assets/icons/profile.png")
const rice = require("../assets/icons/rice.png")
const search = require("../assets/icons/search.png")
const setting = require("../assets/icons/setting.png")
const star = require("../assets/icons/star.png")
const wallet = require("../assets/icons/wallet.png")
const visa = require("../assets/icons/visa.png")

export default {
    apple, back, burger, call, calories, cancel, cart, check_circle, check_off, check_on, cherry, clock, correct, coupon, cross, delete_icon, discount,
    dollar, dotted_line, down_arrow, eye, eye_close, favourite, fb, filter, focus, globe, google, help, home, location, location_pin, logout, love,
    map, mastercard, menu, minus, navigator, navigator1, notification, paypal, plus, profile, rice, search, setting, star, wallet, visa
}